/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import komunikacija.Komunikacija;
import util.Konstante;

/**
 *
 * @author Lazar
 */
public class FrmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
        Komunikacija.getInstance().poveziNaServer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemUnosVezbaca = new javax.swing.JMenuItem();
        jMenuItemPretragaVezbaca = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemUnosTreninga = new javax.swing.JMenuItem();
        jMenuItemPretragaTreninga = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemUnosVezbe = new javax.swing.JMenuItem();
        jMenuItemPretragaVezbe = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Vezbac");

        jMenuItemUnosVezbaca.setText("Unos novog vezbaca");
        jMenuItemUnosVezbaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosVezbacaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUnosVezbaca);

        jMenuItemPretragaVezbaca.setText("Pretraga vezbaca");
        jMenuItemPretragaVezbaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretragaVezbacaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPretragaVezbaca);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Trening");

        jMenuItemUnosTreninga.setText("Unos novog treninga");
        jMenuItemUnosTreninga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosTreningaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemUnosTreninga);

        jMenuItemPretragaTreninga.setText("Pretraga treninga");
        jMenuItemPretragaTreninga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretragaTreningaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPretragaTreninga);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Vezba");

        jMenuItemUnosVezbe.setText("Unos nove vezbe");
        jMenuItemUnosVezbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosVezbeActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemUnosVezbe);

        jMenuItemPretragaVezbe.setText("Pretraga vezbe");
        jMenuItemPretragaVezbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretragaVezbeActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemPretragaVezbe);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUnosVezbacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosVezbacaActionPerformed
        // TODO add your handling code here:
        Komunikacija.getInstance().setAktivan_sk(Konstante.OPERACIJA_DODAVANJA_VEZBACA);
        new FrmUnosVezbaca(null).setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosVezbacaActionPerformed

    private void jMenuItemPretragaVezbacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretragaVezbacaActionPerformed
        // TODO add your handling code here:
        Komunikacija.getInstance().setAktivan_sk(Konstante.SK_PRIKAZ);
        new FrmPretragaVezbaca().setVisible(true);
    }//GEN-LAST:event_jMenuItemPretragaVezbacaActionPerformed

    private void jMenuItemUnosTreningaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosTreningaActionPerformed
        // TODO add your handling code here:
        Komunikacija.getInstance().setAktivan_sk(Konstante.OPERACIJA_DODAVANJA_TRENING);
        new FrmUnosTreninga().setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosTreningaActionPerformed

    private void jMenuItemPretragaTreningaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretragaTreningaActionPerformed
        // TODO add your handling code here:
        Komunikacija.getInstance().setAktivan_sk(Konstante.SK_PRIKAZ);
        new FrmPretragaTreninga().setVisible(true);
    }//GEN-LAST:event_jMenuItemPretragaTreningaActionPerformed

    private void jMenuItemUnosVezbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosVezbeActionPerformed
        // TODO add your handling code here:
        Komunikacija.getInstance().setAktivan_sk(Konstante.OPERACIJA_DODAVANJA_VEZBI);
        new FrmUnosVezbe(null).setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosVezbeActionPerformed

    private void jMenuItemPretragaVezbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretragaVezbeActionPerformed
        // TODO add your handling code here:
        Komunikacija.getInstance().setAktivan_sk(Konstante.SK_PRIKAZ);
        new FrmPretragaVezbi().setVisible(true);
    }//GEN-LAST:event_jMenuItemPretragaVezbeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemPretragaTreninga;
    private javax.swing.JMenuItem jMenuItemPretragaVezbaca;
    private javax.swing.JMenuItem jMenuItemPretragaVezbe;
    private javax.swing.JMenuItem jMenuItemUnosTreninga;
    private javax.swing.JMenuItem jMenuItemUnosVezbaca;
    private javax.swing.JMenuItem jMenuItemUnosVezbe;
    // End of variables declaration//GEN-END:variables
}
