/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Trening;
import domen.Vezbe;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import modeli.ModelTabeleVezba;
import util.Konstante;

/**
 *
 * @author luka.marijanovic
 */
public class FrmUnosVezbe extends javax.swing.JFrame {

    /**
     * Creates new form FrmUnosVezbe
     */
    public FrmUnosVezbe(Vezbe vezba) {
        initComponents();
        srediFormuPremaSK();
    }

    private FrmUnosVezbe() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonSacuvaj = new javax.swing.JButton();
        jTextFieldNaziv = new javax.swing.JTextField();
        jTextFieldFokus = new javax.swing.JTextField();
        jTextFieldVremeTrajanja = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naziv:");

        jLabel2.setText("Fokus:");

        jLabel3.setText("Vreme trajanja:");

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSacuvaj)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jTextFieldFokus)
                            .addComponent(jTextFieldVremeTrajanja))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldFokus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButtonSacuvaj)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        try {
            // TODO add your handling code here:
            String naziv = jTextFieldNaziv.getText();
            String fokus = jTextFieldFokus.getText();
            int vremetrajanja = Integer.parseInt(jTextFieldVremeTrajanja.getText());
            
            if(jTextFieldNaziv.getText().isEmpty() || jTextFieldFokus.getText().isEmpty() || jTextFieldVremeTrajanja.getText().isEmpty()){
                prikaziPorukuGreske("Morate popuniti sva polja");
                return;
            }
            Vezbe vezba = new Vezbe(-1, naziv, fokus, vremetrajanja);
            Komunikacija.getInstance().sacuvajVezbu(vezba);
             obrisiPodatkeIzPolja();
            prikaziPorukuObavestenja("Sistem je zapamtio vezbu");
        } catch (Exception ex) {
           prikaziPorukuGreske("Nije sacuvana vezba");
        }
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUnosVezbe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUnosVezbe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUnosVezbe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUnosVezbe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUnosVezbe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldFokus;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldVremeTrajanja;
    // End of variables declaration//GEN-END:variables
public void srediFormuPremaSK(){
    int aktivanSK = Komunikacija.getInstance().getAktivan_sk();
    
    if(aktivanSK == Konstante.SK_DODAVANJE){
        srediFormu();
        this.setTitle("Unos nove vezbe");
    }
    if(aktivanSK == Konstante.SK_IZMENA){
        srediFormu();
        prikaziPodatkeVezbi(Komunikacija.getInstance().getVezbe());
        this.setTitle("Izmena vezbe");
    } 
    
      if(aktivanSK == Konstante.SK_PRIKAZ){
        jTextFieldNaziv.setEnabled(false);
        jTextFieldFokus.setEnabled(false);
        jTextFieldVremeTrajanja.setEnabled(false);
        prikaziPodatkeVezbi(Komunikacija.getInstance().getVezbe());
        this.setTitle("Detalji vezbe");
    }
}
   
    public void srediFormu(){
    jTextFieldNaziv.setEnabled(true);
    jTextFieldFokus.setEnabled(true);
    jTextFieldVremeTrajanja.setEnabled(true);
}

private void prikaziPorukuGreske(String poruka) {
        JOptionPane.showMessageDialog(this, poruka, "Greška!", JOptionPane.ERROR_MESSAGE);
    }

    private void prikaziPorukuObavestenja(String poruka) {
        JOptionPane.showMessageDialog(this, poruka, "Obaveštenje!", JOptionPane.INFORMATION_MESSAGE);
    }
    
     private void obrisiPodatkeIzPolja() {       
        jTextFieldNaziv.setText("");
        jTextFieldFokus.setText("");
        jTextFieldVremeTrajanja.setText("");
        
    }
     
     private void prikaziPodatkeVezbi(Vezbe vezba){
        jTextFieldNaziv.setText(vezba.getNaziv());
        jTextFieldFokus.setText(vezba.getFokus()); 
        jTextFieldVremeTrajanja.setText(Integer.toString(vezba.getVremeTrajanja()));
     }

    

}
