/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Vezbac;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import util.Konstante;

/**
 *
 * @author Lazar
 */
public class FrmUnosVezbaca extends javax.swing.JFrame {

    public Vezbac v;
    /**
     * Creates new form UnosVezbaca
     */
    public FrmUnosVezbaca(Vezbac vezbac) {
        initComponents();
        srediFormuPremaSK();
        this.v = vezbac;
        Komunikacija.getInstance().setFrmUnosVezbaca(this);
    }

    private FrmUnosVezbaca() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldVisina = new javax.swing.JTextField();
        jTextFieldTezina = new javax.swing.JTextField();
        jTextFieldClanarina = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ime:*");

        jLabel2.setText("Prezime:*");

        jLabel3.setText("Visina:*");

        jLabel4.setText("Tezina:*");

        jLabel5.setText("Clanarina:*");

        jButton1.setText("Sacuvaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIme)
                            .addComponent(jTextFieldPrezime)
                            .addComponent(jTextFieldVisina)
                            .addComponent(jTextFieldTezina)
                            .addComponent(jTextFieldClanarina, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldVisina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTezina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldClanarina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:            
    try{
        String ime = jTextFieldIme.getText();
        String prezime = jTextFieldPrezime.getText();
        double visina = Double.parseDouble(jTextFieldVisina.getText());
        double tezina = Double.parseDouble(jTextFieldTezina.getText());
        int clanarina = Integer.parseInt(jTextFieldClanarina.getText());
        
        
            if (ime == null || ime.isEmpty()) {
                prikaziPorukuGreske("Niste uneli ime vezbaca!");
                return;
            }

            if (prezime == null || prezime.isEmpty()) {
                prikaziPorukuGreske("Niste uneli prezime vezbaca!");
                return;
            }
            
             if (jTextFieldVisina.getText() == null || jTextFieldVisina.getText().isEmpty()) {

                prikaziPorukuGreske("Niste uneli visinu vezbaca!");
                return;
            }

            if (jTextFieldTezina.getText() == null || jTextFieldTezina.getText().isEmpty()) {
                prikaziPorukuGreske("Niste uneli tezinu vezbaca!");
                return;
            }
            
             if (jTextFieldClanarina.getText() == null || jTextFieldClanarina.getText().isEmpty()) {
                prikaziPorukuGreske("Niste uneli clanarinu vezbaca!");
                return;
            }
             
             Vezbac vezbac = new Vezbac();
             vezbac.setIme(ime);
             vezbac.setPrezime(prezime);
             vezbac.setVisina(visina);
             vezbac.setTezina(tezina);
             vezbac.setClanarina(clanarina);
             
             if(Komunikacija.getInstance().getAktivan_sk() == Konstante.OPERACIJA_DODAVANJA_VEZBACA){
                 Komunikacija.getInstance().sacuvajVezbaca(vezbac);
                prikaziPorukuObavestenja("Sistem je zapamtio novog vezbaca!");
                obrisiPodatkeIzPolja();
             }
             
              if(Komunikacija.getInstance().getAktivan_sk() == Konstante.OPERACIJA_IZMENI_VEZBACE){
                  vezbac.setId(v.getVezbacID());
                 Komunikacija.getInstance().izmeniVezbaca(vezbac);
                prikaziPorukuObavestenja("Sistem je zapamtio novog vezbaca!");
                obrisiPodatkeIzPolja();
             }
             
              }
              catch(Exception ex){
                   if (ex.getMessage() != null && ex.getMessage().equals(Konstante.PORUKA_DA_VEC_POSTOJI)) {
                prikaziPorukuGreske("Već je unet ovakav vezbac!");
                return;
              }
                    prikaziPorukuGreske("Sistem ne može da zapamti vezbaca!");
              }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUnosVezbaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUnosVezbaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUnosVezbaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUnosVezbaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUnosVezbaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldClanarina;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    private javax.swing.JTextField jTextFieldTezina;
    private javax.swing.JTextField jTextFieldVisina;
    // End of variables declaration//GEN-END:variables
public void srediFormuPremaSK(){
    int aktivanSK = Komunikacija.getInstance().getAktivan_sk();
    
    if(aktivanSK == Konstante.SK_DODAVANJE){
        srediFormu();
        this.setTitle("Unos novog vezbaca");
    }
    if(aktivanSK == Konstante.SK_IZMENA){
        srediFormu();
        prikaziPodatkeVezbaca(Komunikacija.getInstance().getVezbac());
        this.setTitle("Izmena vezbaca");
    }
    
    if(aktivanSK == Konstante.SK_PRIKAZ){
            jTextFieldIme.setEditable(false);
            jTextFieldPrezime.setEditable(false);
            jTextFieldVisina.setEditable(false);
            jTextFieldTezina.setEditable(false);
            jTextFieldClanarina.setEditable(false);
            jButton1.setVisible(false);

            
            prikaziPodatkeVezbaca(Komunikacija.getInstance().getVezbac());
        }
    
}
    
    public void srediFormu(){
    jTextFieldIme.setEnabled(true);
    jTextFieldPrezime.setEnabled(true);
    jTextFieldVisina.setEnabled(true);
    jTextFieldTezina.setEnabled(true);
    jTextFieldClanarina.setEnabled(true);
}

private void prikaziPorukuGreske(String poruka) {
        JOptionPane.showMessageDialog(this, poruka, "Greška!", JOptionPane.ERROR_MESSAGE);
    }

    private void prikaziPorukuObavestenja(String poruka) {
        JOptionPane.showMessageDialog(this, poruka, "Obaveštenje!", JOptionPane.INFORMATION_MESSAGE);
    }
    
     private void obrisiPodatkeIzPolja() {
        
        
        jTextFieldIme.setText("");
        jTextFieldPrezime.setText("");
        jTextFieldVisina.setText("");
        jTextFieldTezina.setText("");
        jTextFieldClanarina.setText("");
        
    }
     
     private void prikaziPodatkeVezbaca(Vezbac vezbac){
        jTextFieldIme.setText(vezbac.getIme());
        jTextFieldPrezime.setText(vezbac.getPrezime());
        jTextFieldVisina.setText(Double.toString(vezbac.getVisina()));
        jTextFieldTezina.setText(Double.toString(vezbac.getTezina()));
        jTextFieldClanarina.setText(Integer.toString(vezbac.getClanarina()));
        
     }

}
